# Project information
site_name: Nobius
site_author: Pierre Tharreau, Louis Manestar
site_description: >-
  Nobius, a set of utilities which generate and manage large amounts of
  Mobius content.

# Git repo information
repo_url: https://github.com/Loumstar/Nobius
repo_name: Nobius (private)

# Page Tree
nav:
  - Welcome!: index.md
  - Quickstart Guide: quickstart.md
  - About:
      - List of Features: "About/features.md"
  - Usage:
      - generateGroup.py: "Usage/generateGroup.md"
      - generateJSON.py: "Usage/generateJSON.md"
      - generateAll.py: "Usage/generateAll.md"
  - Sheet Files:
      - Sheet File Structure: "SheetFiles/SheetFileStructure.md"
      - SheetInfo.json: "SheetFiles/SheetInfo.md"
      - Question files: "SheetFiles/Questions.md"
      - Parts: "SheetFiles/Parts.md"
  - Response areas:
      - Vanilla:
          - List: "ResponseAreas/Vanilla/list.md"
          - Maple Graded: "ResponseAreas/Vanilla/maple.md"
          - Multiple Choice: "ResponseAreas/Vanilla/multiple_choice.md"
          - True False: "ResponseAreas/Vanilla/true_false.md"
          - Numeric: "ResponseAreas/Vanilla/numeric.md"
      - Advanced:
          - Matrix: "ResponseAreas/Advanced/matrix.md"
          - Custom: "ResponseAreas/Advanced/custom.md"
  - Customization and Resources:
      - QuestionJavascript: "CustomizationAndResources/QuestionJavascript.md"
      - Templates and Jinja: "CustomizationAndResources/TemplatesAndJinja.md"
  - Addons/Features:
      - Future additions/changes: "AddonsAndFeatures/FutureAdditions.md"

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/eye
        name: Switch to light mode

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
